### PR TITLE
slight refactor to fix #53 fix #52

### LINKED ISSUE #52: update instance type
https://github.com/moka-guys/benchmarking_tool/blob/65c778b620b88a17813f01493c8ba480b1470000/happy_vcfeval/precision_medicine.py#L287

### LINKED ISSUE #53: use dx describe to check specific jobid - then don't need to have a max time frame
https://github.com/moka-guys/benchmarking_tool/blob/65c778b620b88a17813f01493c8ba480b1470000/happy_vcfeval/precision_medicine.py#L343

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/benchmarking_tool/54)

### CODE REVIEW

**Review by natashapinto — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/benchmarking_tool/54)* status: all files reviewed, 3 unresolved discussions (waiting on @aledj2)

___
*[`happy_vcfeval/precision_medicine.py` line 377 at r1](https://reviewable.io/reviews/moka-guys/benchmarking_tool/54#-NdGRXWTEH3EDw5TEBsX:-NdGRXWTEH3EDw5TEBsY:b-4vlp5y) ([raw file](https://github.com/moka-guys/benchmarking_tool/blob/d0e0fe25aecfcca78c7dc9b4773af21754a6ea97/happy_vcfeval/precision_medicine.py#L377)):*
> ```Python
>             # close file
>             summary_csv.close()
>             print snp_recall,snp_recall_lowerCI, snp_recall_upperCI, snp_precision,snp_precision_lowerCI,snp_precision_upperCI
> ```

why are these being printed?
___
*[`happy_vcfeval/precision_medicine.py` line 391 at r1](https://reviewable.io/reviews/moka-guys/benchmarking_tool/54#-NdGRt5q-xFbfSnzaS7e:-NdGRt5q-xFbfSnzaS7f:bnj7hl0) ([raw file](https://github.com/moka-guys/benchmarking_tool/blob/d0e0fe25aecfcca78c7dc9b4773af21754a6ea97/happy_vcfeval/precision_medicine.py#L391)):*
> ```Python
>             if snps_found:
>                 email_message += "\nSNP recall (sensitivity)={recall} (95% CI: {recall_lower}-{recall_upper})\nSNP precision (PPV) = {precision} (95% CI: {precision_lower}-{precision_upper})".format(recall = snp_recall, recall_lower = snp_recall_lowerCI, recall_upper = snp_recall_upperCI, precision = snp_precision,precision_lower = snp_precision_lowerCI,precision_upper = snp_precision_upperCI)
>                 print "390: %s" %  email_message
> ```

same as above
___
*[`happy_vcfeval/run_code_outside_django.py` line 21 at r1](https://reviewable.io/reviews/moka-guys/benchmarking_tool/54#-NdGSpgf-WPKppi_JiCE:-NdGSpgg8w1IDN0dphgG:b-3pdo37) ([raw file](https://github.com/moka-guys/benchmarking_tool/blob/d0e0fe25aecfcca78c7dc9b4773af21754a6ea97/happy_vcfeval/run_code_outside_django.py#L21)):*
> ```Python
>     upload.take_inputs(email, vcf_filepath, bed_filepath, genome_build)
> 
> email="aledjones@nhs.net"
> ```

Should we use mokaguys account instead?

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/benchmarking_tool/54)* status: all files reviewed, 3 unresolved discussions (waiting on @natashapinto)

___
*[`happy_vcfeval/precision_medicine.py` line 377 at r1](https://reviewable.io/reviews/moka-guys/benchmarking_tool/54#-NdGRXWTEH3EDw5TEBsX:-NdGUrBuEMRDEgiF9uH-:b57yzcz) ([raw file](https://github.com/moka-guys/benchmarking_tool/blob/d0e0fe25aecfcca78c7dc9b4773af21754a6ea97/happy_vcfeval/precision_medicine.py#L377)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

why are these being printed?
</blockquote></details>

oh good spot
___
*[`happy_vcfeval/precision_medicine.py` line 391 at r1](https://reviewable.io/reviews/moka-guys/benchmarking_tool/54#-NdGRt5q-xFbfSnzaS7e:-NdGUsuK1l4UFyF-mAuS:b57yzcz) ([raw file](https://github.com/moka-guys/benchmarking_tool/blob/d0e0fe25aecfcca78c7dc9b4773af21754a6ea97/happy_vcfeval/precision_medicine.py#L391)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

oh good spot
___
*[`happy_vcfeval/run_code_outside_django.py` line 21 at r1](https://reviewable.io/reviews/moka-guys/benchmarking_tool/54#-NdGSpgf-WPKppi_JiCE:-NdGUuS5BdUCe7KmcF9Y:bt68u2q) ([raw file](https://github.com/moka-guys/benchmarking_tool/blob/d0e0fe25aecfcca78c7dc9b4773af21754a6ea97/happy_vcfeval/run_code_outside_django.py#L21)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

Should we use mokaguys account instead?
</blockquote></details>

this is just used for testing to replicate the user's email form the website and can be changed each time  - mokaguys gets a copy also

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/benchmarking_tool/54)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @natashapinto)

___
*[`happy_vcfeval/precision_medicine.py` line 377 at r1](https://reviewable.io/reviews/moka-guys/benchmarking_tool/54#-NdGRXWTEH3EDw5TEBsX:-NdGW1YF5ClSAcoWv7Zw:b-7rl0kd) ([raw file](https://github.com/moka-guys/benchmarking_tool/blob/d0e0fe25aecfcca78c7dc9b4773af21754a6ea97/happy_vcfeval/precision_medicine.py#L377)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

oh good spot
</blockquote></details>

done
___
*[`happy_vcfeval/precision_medicine.py` line 391 at r1](https://reviewable.io/reviews/moka-guys/benchmarking_tool/54#-NdGRt5q-xFbfSnzaS7e:-NdGW3KC0VlnIJyQ4DAl:bb7f2mf) ([raw file](https://github.com/moka-guys/benchmarking_tool/blob/d0e0fe25aecfcca78c7dc9b4773af21754a6ea97/happy_vcfeval/precision_medicine.py#L391)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

oh good spot
</blockquote></details>

done

**Review by natashapinto — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/benchmarking_tool/54)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aledj2)

**Pull request merged**
